### ISSUE TITLE
Add litellm integration - Add support for Azure OpenAI , OpenAI, Palm, VertexAI, SageMaker, Bedrock, Replicate (100+ LLMs)

### ISSUE THREAD

**Issue by navicstein** [langchain-ai/langchain-extract#115]
We should add support for litellm. https://github.com/BerriAI/litellm/

LiteLLM is a lightweight package to simplify LLM API calls.

Adding support for LiteLLM integration will enhance the capabilities of the project by providing a lightweight package to simplify LLM API calls. This will enable us to easily access and utilize various LLMs, including Azure OpenAI, OpenAI, Palm, VertexAI, SageMaker, Bedrock, Replicate, and many more.

and a lot of recently released models supports JSON and could be used with Ollama, I’m open to create a PR if this is the right way to go

**Comment by eyurtsev** [comment]
This isn't something we're interested in supporting. langchain-extract is a use case accelerator for the LangChain eco system, and we'll be only on LangChain chat llm integrations.
