### ISSUE TITLE
Azure OpenAI

### ISSUE THREAD

**Issue by shima-khoshraftar** [langchain-ai/langchain-extract#19]
Hi, I am wondering if you have support for Azure OpenAI. For Azure OpenAI, in addition to OPENAI_API_KEY, there are azure_endpoint and api_version parameters needed. I added them to the .local.env file in the next two lines after api_key but I get an api_key error which shows the next two lines were not read or used.  Thanks.

**Comment by eyurtsev** [comment]
yes! but you need to modify the code right now to use the azure openai https://python.langchain.com/docs/integrations/chat/azure_chat_openai

any of langchain chat models llms will work, but this is right now meant as a bare bones service so you need to adapt the code to your own needs

**Comment by shima-khoshraftar** [comment]
Thanks for your reply. Yes, I added that.
